/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(adsb_mod_async.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e3345739e3150eac7ad0625ce805e9fc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/spoof1090/adsb_mod_async.h>
// pydoc.h is automatically generated in the build directory
#include <adsb_mod_async_pydoc.h>

void bind_adsb_mod_async(py::module& m)
{

    using adsb_mod_async    = gr::spoof1090::adsb_mod_async;


    py::class_<adsb_mod_async, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<adsb_mod_async>>(m, "adsb_mod_async", D(adsb_mod_async))

        .def(py::init(&adsb_mod_async::make),
           D(adsb_mod_async,make)
        )
        



        ;




}








