/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-spoof1090
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SPOOF1090_API_H
#define INCLUDED_SPOOF1090_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_spoof1090_EXPORTS
#define SPOOF1090_API __GR_ATTR_EXPORT
#else
#define SPOOF1090_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SPOOF1090_API_H */
